# Generated by Django 5.1.3 on 2025-04-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_data_posted_post_date_posted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="context",
            new_name="content",
        ),
    ]
