# Generated by Django 5.1.3 on 2025-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
