# Generated by Django 5.1.3 on 2025-04-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_tag_tag_slug_alter_post_tags_alter_tag_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_slug",
            field=models.SlugField(default=None, max_length=20, null=True, unique=True),
        ),
    ]
