# Generated by Django 5.1.3 on 2025-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_tag_tag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tag_slug",
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
