# Generated by Django 5.1.3 on 2025-04-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_tag_tag_slug_alter_post_tags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
